
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: arkausers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  user-service:
    build: ./user-service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: arkausers
      DB_USER: postgres
      DB_PASSWORD: postgres
      SECURITY_JWT_SECRET: short_secret_key_32_chars_len!!!
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    # healthcheck to ensure app is up
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 40
volumes:
  pgdata:
